-- Restaurant Admin Portal foundation.
-- This migration is intentionally additive and keeps the legacy "admin" role valid.

do $$
declare
  constraint_record record;
begin
  for constraint_record in
    select conname
    from pg_constraint
    where conrelid = 'public.admin_users'::regclass
      and contype = 'c'
      and pg_get_constraintdef(oid) ilike '%role%'
  loop
    execute format('alter table public.admin_users drop constraint if exists %I', constraint_record.conname);
  end loop;
exception
  when undefined_table then
    null;
end $$;

do $$
begin
  if to_regclass('public.admin_users') is not null
    and not exists (
      select 1
      from pg_constraint
      where conrelid = 'public.admin_users'::regclass
        and conname = 'admin_users_role_check_v2'
    )
  then
    alter table public.admin_users
      add constraint admin_users_role_check_v2
      check (role in ('admin', 'superadmin', 'hr_admin', 'territory_admin', 'restaurant_admin'));
  end if;
end $$;

do $$
declare
  constraint_record record;
begin
  for constraint_record in
    select conname
    from pg_constraint
    where conrelid = 'public.admin_access_audit'::regclass
      and contype = 'c'
      and pg_get_constraintdef(oid) ilike '%assigned_role%'
  loop
    execute format('alter table public.admin_access_audit drop constraint if exists %I', constraint_record.conname);
  end loop;
exception
  when undefined_table then
    null;
end $$;

do $$
begin
  if to_regclass('public.admin_access_audit') is not null
    and not exists (
      select 1
      from pg_constraint
      where conrelid = 'public.admin_access_audit'::regclass
        and conname = 'admin_access_audit_assigned_role_check_v2'
    )
  then
    alter table public.admin_access_audit
      add constraint admin_access_audit_assigned_role_check_v2
      check (
        assigned_role is null
        or assigned_role in ('admin', 'superadmin', 'hr_admin', 'territory_admin', 'restaurant_admin')
      );
  end if;
end $$;

create table if not exists public.admin_restaurant_access (
  id bigint generated by default as identity primary key,
  admin_user_id bigint null references public.admin_users(id) on delete cascade,
  admin_email text null,
  restaurant_id bigint not null references public.restaurants(id) on delete cascade,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint admin_restaurant_access_admin_target_check
    check (admin_user_id is not null or nullif(trim(admin_email), '') is not null)
);

create index if not exists idx_admin_restaurant_access_restaurant_id
  on public.admin_restaurant_access (restaurant_id)
  where is_active = true;

create index if not exists idx_admin_restaurant_access_admin_user_id
  on public.admin_restaurant_access (admin_user_id)
  where is_active = true;

create index if not exists idx_admin_restaurant_access_admin_email
  on public.admin_restaurant_access ((lower(admin_email)))
  where is_active = true and admin_email is not null;

create unique index if not exists uq_admin_restaurant_access_user_restaurant_active
  on public.admin_restaurant_access (admin_user_id, restaurant_id)
  where is_active = true and admin_user_id is not null;

create unique index if not exists uq_admin_restaurant_access_email_restaurant_active
  on public.admin_restaurant_access ((lower(admin_email)), restaurant_id)
  where is_active = true and admin_email is not null;

alter table if exists public.slots
  add column if not exists needed_count integer not null default 1,
  add column if not exists accepted_count integer not null default 0;

do $$
begin
  if to_regclass('public.slots') is not null
    and not exists (
      select 1
      from pg_constraint
      where conrelid = 'public.slots'::regclass
        and conname = 'slots_needed_count_positive_check'
    )
  then
    alter table public.slots
      add constraint slots_needed_count_positive_check
      check (needed_count >= 1);
  end if;

  if to_regclass('public.slots') is not null
    and not exists (
      select 1
      from pg_constraint
      where conrelid = 'public.slots'::regclass
        and conname = 'slots_accepted_count_non_negative_check'
    )
  then
    alter table public.slots
      add constraint slots_accepted_count_non_negative_check
      check (accepted_count >= 0);
  end if;
end $$;

create index if not exists idx_slots_restaurant_status_date
  on public.slots (restaurant_id, status, work_date);

create index if not exists idx_applications_slot_status
  on public.applications (slot_id, status);

update public.slots s
set accepted_count = coalesce(a.accepted_count, 0)
from (
  select slot_id, count(*)::integer as accepted_count
  from public.applications
  where status = 'approved'
  group by slot_id
) a
where s.id = a.slot_id;

update public.slots
set accepted_count = 0
where accepted_count is null;

update public.slots
set status = case
  when status = 'closed' then 'closed'
  when accepted_count >= needed_count then 'assigned'
  else 'open'
end
where status in ('open', 'pending', 'assigned');

create or replace function public.sync_slot_capacity_from_applications()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  target_slot_id bigint;
  approved_total integer;
  target_needed integer;
  current_status text;
begin
  for target_slot_id in
    select distinct slot_id
    from (
      values
        (case when tg_op <> 'INSERT' then old.slot_id else null end),
        (case when tg_op <> 'DELETE' then new.slot_id else null end)
    ) as changed_slots(slot_id)
    where slot_id is not null
  loop
    select
      greatest(coalesce(needed_count, 1), 1),
      status
    into target_needed, current_status
    from public.slots
    where id = target_slot_id;

    if not found then
      continue;
    end if;

    select count(*)::integer
    into approved_total
    from public.applications
    where slot_id = target_slot_id
      and status = 'approved';

    update public.slots
    set
      accepted_count = approved_total,
      status = case
        when current_status = 'closed' then 'closed'
        when approved_total >= target_needed then 'assigned'
        else 'open'
      end
    where id = target_slot_id;
  end loop;

  return coalesce(new, old);
end;
$$;

create or replace function public.prevent_slot_overbooking()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  target_needed integer;
  current_status text;
  approved_total integer;
begin
  if new.status is distinct from 'approved' then
    return new;
  end if;

  if tg_op = 'UPDATE'
    and old.status = 'approved'
    and old.slot_id = new.slot_id
  then
    return new;
  end if;

  select
    greatest(coalesce(needed_count, 1), 1),
    status
  into target_needed, current_status
  from public.slots
  where id = new.slot_id
  for update;

  if not found then
    raise exception 'Слот не найден';
  end if;

  if current_status = 'closed' then
    raise exception 'Слот закрыт';
  end if;

  select count(*)::integer
  into approved_total
  from public.applications
  where slot_id = new.slot_id
    and status = 'approved'
    and id is distinct from new.id;

  if approved_total >= target_needed then
    raise exception 'Слот уже укомплектован';
  end if;

  return new;
end;
$$;

drop trigger if exists trg_prevent_slot_overbooking on public.applications;

create trigger trg_prevent_slot_overbooking
before insert or update
on public.applications
for each row
execute function public.prevent_slot_overbooking();

drop trigger if exists trg_sync_slot_capacity_from_applications on public.applications;

create trigger trg_sync_slot_capacity_from_applications
after insert or update or delete
on public.applications
for each row
execute function public.sync_slot_capacity_from_applications();
