create table if not exists public.telegram_links (
  user_id uuid primary key,
  email text not null,
  telegram_user_id bigint not null unique,
  chat_id bigint not null,
  telegram_username text null,
  telegram_first_name text null,
  telegram_last_name text null,
  is_active boolean not null default true,
  linked_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_telegram_links_email
  on public.telegram_links ((lower(email)));

create index if not exists idx_telegram_links_active
  on public.telegram_links (is_active);

create table if not exists public.telegram_notification_settings (
  user_id uuid primary key,
  is_enabled boolean not null default true,
  updated_at timestamptz not null default now()
);

create table if not exists public.telegram_link_tokens (
  token text primary key,
  user_id uuid not null,
  email text not null,
  expires_at timestamptz not null,
  used_at timestamptz null,
  created_at timestamptz not null default now()
);

create index if not exists idx_telegram_link_tokens_user_id
  on public.telegram_link_tokens (user_id);

create index if not exists idx_telegram_link_tokens_expires_at
  on public.telegram_link_tokens (expires_at);

create table if not exists public.telegram_notification_jobs (
  id bigint generated by default as identity primary key,
  user_id uuid not null,
  kind text not null,
  payload jsonb not null default '{}'::jsonb,
  scheduled_for timestamptz not null default now(),
  status text not null default 'pending' check (
    status in ('pending', 'sent', 'error', 'cancelled')
  ),
  created_at timestamptz not null default now(),
  sent_at timestamptz null,
  error_message text null
);

create index if not exists idx_telegram_notification_jobs_pending
  on public.telegram_notification_jobs (status, scheduled_for);

create table if not exists public.telegram_notification_log (
  id bigint generated by default as identity primary key,
  user_id uuid not null,
  application_id bigint null,
  job_id bigint null,
  telegram_user_id bigint null,
  notification_kind text not null,
  status text not null check (
    status in ('sent', 'error', 'skipped')
  ),
  payload jsonb not null default '{}'::jsonb,
  sent_at timestamptz not null default now(),
  error_message text null
);

create index if not exists idx_telegram_notification_log_user_id
  on public.telegram_notification_log (user_id);

create index if not exists idx_telegram_notification_log_sent_at
  on public.telegram_notification_log (sent_at desc);

create unique index if not exists uq_telegram_shift_notification_once
  on public.telegram_notification_log (application_id, notification_kind)
  where application_id is not null and status = 'sent';