create table if not exists public.admin_access_audit (
  id bigint generated by default as identity primary key,
  actor_user_id uuid null,
  actor_email text not null,
  target_email text not null,
  action text not null check (action in ('grant', 'revoke')),
  assigned_role text null check (
    assigned_role is null
    or assigned_role in ('admin', 'superadmin')
  ),
  created_at timestamptz not null default now()
);

create index if not exists idx_admin_access_audit_created_at
  on public.admin_access_audit (created_at desc);

create index if not exists idx_admin_access_audit_target_email
  on public.admin_access_audit ((lower(target_email)));

create index if not exists idx_admin_access_audit_actor_email
  on public.admin_access_audit ((lower(actor_email)));